---
abstract: 'A smaller and more communicable pseudo-UUID'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Data::UUID: 0
  Encode::Base32::Crockford: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-TUID
recommends:
  Data::LibUUID: 0
requires: {}
version: 0.0111_2
