---
abstract: 'A smaller and more communicable pseudo-UUID'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-TUID
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::UUID::LibUUID: 0
  Encode::Base32::Crockford: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/Data-TUID/tree/master
version: 0.01
